sonar.organization=kitten16-designer
sonar.projectKey=Kitten16-designer_APP-Seminario-Machala

sonar.sources=.
sonar.exclusions=venv/**,tests/**

sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
